### ISSUE TITLE
InstaSwap - ERC-1155 token exchange on Starknet

### ISSUE THREAD

**Issue by metaforoadmin** [BibliothecaDAO/Frontinus-House-Docs#12]
InstaSwap operates as a decentralized protocol tailored for exchanging ERC-1155 tokens on Starknet. Essentially, it functions comparably to Uniswap but within the context of ERC-1155 tokens. Users can conveniently conduct transactions involving up to 'n' ERC1155 tokens, facilitated by an ERC20 token, all within a single trade.

The inception of InstaSwap draws significant inspiration from distinguished platforms like Uniswap and Niftyswap. The project's initiation was catalyzed by the efforts of Lord Loaf, who kickstarted the project by crafting the contracts in Cairo 0. Later, FelixGibson Felix Luo elevated the endeavor by advancing the contracts to Cairo 1. Metaforo is joining the league to further expand its horizons, aiming to deliver an unparalleled trading experience within the Starknet ecosystem. InstaSwap will be the first 1155 AMM swap on Starknet, enabling the trading of in-game assets outside of the game environment. In the future, we will also support the trading of ERC20 and ERC721 assets.

### **Introduction**
Name or social handle of proposer: Yao
Partners:  [Felix Luo](https://github.com/FelixGibson)
Ethereum Mainnet Address: 0x15680E931b0A6918674BD5fE9b31c268A8f12B88

Any relevant links/Websites (optional): 
[Github Repo](https://github.com/BibliothecaDAO/InstaSwap)
[Figma link](https://www.figma.com/file/ejAHO8fklwWlZHdMoU8jZJ/InstaSwap?type=design&node-id=0%3A1&mode=design&t=pi4Gb2HRrtzy9Bjb-1)
![image](https://github.com/Calcutatator/Frontinus-House-Docs/assets/99704044/49871225-a921-41c3-b16a-ed9915bb8213)

### **Project Detail**
**Project Overview:**

The proposed project, InstaSwap, introduces a pioneering decentralized token swap protocol for ERC-1155 tokens, exclusively designed for deployment on the Starknet platform.This initiative draws inspiration from successful platforms like Uniswap and Niftyswap.  This endeavor holds significance as it marks the inception of the first-ever ERC-1155 token swap mechanism within the Starknet ecosystem.

**Uniqueness and Distinction:**

What truly sets InstaSwap apart is its groundbreaking nature as the inaugural ERC-1155 token swap solution on Starknet. While other platforms may have paved the way for decentralized exchanges and token swaps, InstaSwap's uniqueness lies in its role as a trailblazer within the Starknet domain. This project introduces an unprecedented means for users to trade ERC-1155 tokens in a decentralized manner on this specific blockchain network.

**Target Audience:**

InstaSwap's primary target audience comprises holders, traders, and enthusiasts of ERC-1155 tokens who are vested in the Starknet ecosystem. By offering a tailored solution for ERC-1155 tokens within this unique blockchain framework, InstaSwap aims to cater to the distinct needs of this audience, ensuring seamless token swaps while aligning with the principles of decentralization.

**Excitement and Vision:**

The prospect of building InstaSwap is exceptionally exhilarating due to its potential to spearhead innovation within the Starknet ecosystem. This project embodies the fusion of cutting-edge blockchain technology and decentralized finance, unlocking the doors to efficient, secure, and transparent ERC-1155 token swaps. The excitement stems from the opportunity to be at the forefront of a new era of trading possibilities on Starknet.

In conclusion, InstaSwap's distinction as the pioneer of ERC-1155 token swaps on Starknet underscores its unique value proposition. This project holds immense potential to catalyze innovation within the Starknet ecosystem, opening doors to new avenues of decentralized trading and contributing to the growth of decentralized finance (DeFi) as a whole.

### **Character**
The developers spearheading the construction of InstaSwap-
**FelixGibson:** Passionate about web3, open source, and community-driven projects. Proficient in Cairo, React, and Java with a focus on creating impactful and user-centric experiences.

**Yao**: With a solid decade of experience as a full-stack engineer and 2 years dedicated to crypto development, Yao brings a wealth of expertise to the table. He is a fervent advocate for on-chain games, holding a strong belief in their potential. Beyond that, Yao is deeply enthusiastic about DAOs and have actively contributed as both an enthusiast and a builder of DAO tooling.

**6V**: Dedicated to community-driven projects, open source, and the exciting realm of web3. Adept in Java, React, and Cairo, with a passion for designing impactful and user-centric experiences.

The expertise of this developer group showcases our dedication to crafting custom solutions for the Web3 arena. Our adeptness in governance mechanisms, Web3 systems, and innovative thinking equips us well to address InstaSwap's challenges. Metaforo's ability to build on strong foundations and add innovative features illustrates our flexibility in the dynamic StarkNet Ecosystem.

### **Timeline**
We aim to initiate the project on September 5, 2023, and release the product for alpha testing at the beginning of December. Beta testing is slated for January 2024.

### **Objectives**
| Objectives  | Contributors | Due Date  | 
| ------------- | ------------- |------------- | 
| UI and UX design finalized using Figma  | Yao | 9/15/2023 | 
| Cairo Contracts | Felix  | 9/30/2023  | 
| Complete the development of the JavaScript SDK based on ERC-1155 smart contracts. | Felix & Yao  | 10/15/2023  | 
| Conclude the development of the frontend framework | Felix & Yao  | 11/15/2023  | 
| Wrap up InstaSwap development (UI) for alpha testing. | Yao & 6v | 12/15/2023 | 
| Release the beta version of InstaSwap. | Yao  | 1/15/2024 | 

### **Grant Request**
100,000 $LORDS

**Comment by Calcutatator** [comment]
Really great proposal sers. Good to see it's already started work and is a totally missing piece of the puzzle for starknet as a whole.

Will be a great component within Realms.world!

**Comment by palomato** [comment]
Definitely interested in this. Great proposal 👍

- Is InstaSwap its own DEX on StarkNet and BibDAO is allowed to deploy a DAO-owned/branded instance on our own appchain? Or will BibDAO own the InstaSwap DEX on StarkNet also?

- UniV3 repo was originally released with a Business Source License 1.1 (BSL-1.1) to prevent forking. If the DAO is paying for work, should the InstaSwap repo also have a license? (open question, want to know what you think)

- The linked Figmas for the web UI look like ERC-721 (NFT) markets to me. Would love to see your thoughts on swap screens for ERC-20s->ERC-1155s (like your last Figma screen, explore-Marketplaces). I assume something like UniSwap UI?

> Users can conduct transactions involving up to 'n' ERC1155 tokens, facilitated by an ERC20 token, all within a single trade

- So I can sell multiple ERC-1155s for an ERC-20. Do the contracts allow for the reverse--sell one ERC-1155 for multiple ERC-20s?

Thanks for building this!

**Comment by FelixGibson** [comment]
1. Instapswap is on Starknet, but it's possible to be deployed on appchain as well. And it's owned by BibDAO and BibDAO is allowed to do anything.
2. Current it's on MIT license. Since DAO pays for this work, it can be discussed to change the license.  
3. ERC1155 is a kind of NFT. So we designed it to be more likely a marketplace, just like niftyswap. It's more user-friendly. And add_liquidity, remove_liquidity, swap etc. operation is exactly the same as niftyswap. Since we support swap for multiple ERC1155 tokens, we need a different UI compared to uniswap, which only support swap for one kind of token.
4. No, currently we support swapping multiple ERC1155s for an ERC20, and swapping one kind ERC20 for multiple ERC1155s.

**Comment by AlanMir** [comment]
Really interesting proposal Lords

**Comment by r0man1337** [comment]
Very interested in this. I think almost every game needs an items marketplace, so the need for such a project is beyond doubt. Also like your design. I fully support you!
