### ISSUE TITLE
RAW Ecosystem Chatbot (RAWEC) - New Player On-boarding

### ISSUE THREAD

**Issue by johnbpetersen** [BibliothecaDAO/Frontinus-House-Docs#14]
<h3>Introduction</h3>
<p>Name or social handle of proposer: jbp3</p>
<p>Ethereum Mainnet Address: 0xD314749C5E91e5Ee11d0E5f5cb88ddbBD755F0DD</p>
<p>ENS name (optional): jbp3.eth</p>
<p>Twitter handle (optional): johnbpetersen</p>
<h3>Project Detail</h3>
<p>In order for The Realms Autonomous World vision to become a reality, new player on-boarding will be of vital importance. Eternum is already a complex game with an entire Master Scroll dedicated to educated players, and as we’ve seen with the Frontinus proposals submitted so far, we will have many games in development. It is important that we have a simple and interoperable resource for new players to find their way.</p>
<p>Enter the RAW Ecosystem Chatbot (RAWEC).</p>
<p>RAWEC will be a versatile chatbot utilizing the latest in AI developments and advanced indexing capabilities to produce a seamless new player on-boarding experience.</p>
<p>RAWEC will initially be designed as an efficient knowledge base to guide players in their gaming experience. It will have full working knowledge of all Eternum documentation and lore. Players can ask specific questions like “how can I capture a Relic from another Realm?” or “how does building decay work?”</p>
<p>This grant will cover the creation of RAWEC to provide a superb on-boarding experience for players of Eternum and Loot Survivor with the functionality to ingest and index data for other RAW & Frontinus developed games. Players will be able to interact with RAWEC through Discord.</p>
<p>Further development possibilities that are not part of this scope but could be future additions include:</p>
<ul>
<li>Game event based story telling: “Tell me a detailed story about how my Loot Adventurer died” or “Tell me a story about what happened when I raided that Realm”</li>
<li>Game data integration: “What were the results of my last 5 raids?”</li>
<li>Strategy simulator: “What is the best way for me to increase my resource yield for Realm 7521?”</li>
<li>RAWEC API: for use directly within Eternum, Loot Survivor, and other RAW games</li>
</ul>
<h3>Character</h3>
<p>I’m jbp3. I’ve been an owner and investor in Realms for almost 2 years now. I’ve been a part of Crypts and Caverns since its mint. I’m currently a member of the DAO Council for Crypto Unicorns. Over a decade ago, I founded 2 software development shops where we designed and developed over 35 startups for our clients. I previously led Business Development a Hawku - at premier web3 gaming marketplace - where I spoke to dozens of web3 game teams and communities. New player on boarding is a struggle for almost all of them, and I think we have the chance to build something unique here. Most recently, I was doing some consulting to help a team rapid prototype a few ideas working with the Open AI API. My personal development skills are a bit rusty, but I’m ready to jump back in to build the foundations of RAWEC.</p>
<h3>Timeline</h3>
<p>4 months of total build time to allow for proper input from DAO members as well as feedback, testing and iteration.</p>
<h3>Objectives</h3>

Objective | Contributor | Estimated deadline
-- | -- | --
RAWEC Prototype | jbp3 | 23/11/01
Feedback & testing | jbp3 | 23/12/01
Scaffolding for additional games | jbp3 | 24/01/01

<h3>Grant Request</h3>
<p>100,000 $LORDS</p>

**Comment by Calcutatator** [comment]
gm ser, love to see someone getting back to dev'ing 🤝 

Assuming you have had a look over "Blobert" the AI previously made. New AI advancements will for sure make a newer version far superior but what would you see as the key improvements that can be done compared to the older bot? Thanks!

**Comment by ponderingdemocritus** [comment]
Great idea! I am happy to help architect this with you. I have a good idea of how it should be done.
