### ISSUE TITLE
Starknet.unity

### ISSUE THREAD

**Issue by joellai** [BibliothecaDAO/Frontinus-House-Docs#16]
# Frontinus House Builder Proposal

### Introduction
Name or social handle of proposer: **Joel Lai from iLAYER**

Ethereum Mainnet Address: **0x42415C3FA0F897866FBf8d807168d210a33bed5E**

Twitter handle: **@Joel_Lai_8**

Any relevant links/Websites: **https://github.com/joellai/Starknet.unity**

### Project Detail
**Make the C# script in unity can contact with stark net chain**

The project is named Starknet.unity, it is used to make unity project can contact Starknet in C# script.

As is known,  starknet.js is well-known, which is the main tool bundle for developers to contact the starknet chain. It provides relevant APIs to make the development process smooth. However, there is no something like Starknet.cs to create Starknet unity project easily.

This project is to develop an asset for unity to contact with Starknet. It will provide more convenience for game developers who would like to use Starknet.

### Character
***The Main DEVs***
**Joel Lai**
The game developer of iLAYER, passionate to absorb any new techs and algorithms in computer science, especially cross code for the complicated systems.
***Main Code Area***: Javascript, C#, Rust

**Bill Lee**
The crypto developer of iLAYER, with a decade years of full-stack and comprehensive system build experience, used to work in Tencent and PPTV. Now dive into the crypto world to explore, the previous project is StarShark.
***Main Code Area***: Java, Go, Javascript, Solidity, Cairo.

### Timeline

| Start     | End   | Duration  |
| ------------- |:-------------:| -------------------:|
| 2023/08/30   | 2023/10/14| 2 months            |
### Objectives
| Objective     | Contributor   | Estimated deadline  |
| ------------- |:-------------:| -------------------:|
|  Testify Stark SDK and overwrite the code | Joel Lai | 2023/09/1            |
| Testify the Starknet RPC request and response  | Bill Lee | 2023/9/7            |
|  Basic methods building (deploy, invoke)   | Joel Lai & Bill Lee | 2023/9/20           |
| Comprehensive build with full methods   | Joel Lai & Bill Lee | 2023/10/14            |

### Grant Request
100,000 LORDS for apply from the Frontinus House Genesis Grant.

**Comment by ponderingdemocritus** [comment]
This is well needed - I think you might be able to get a small grant from Starkware directly for this. Also, make yourself known in the dojo discord.

**Comment by joellai** [comment]
> This is well needed - I think you might be able to get a small grant from Starkware directly for this. Also, make yourself known in the dojo discord.

Thanks bro, meet you in DC. : )
