### ISSUE TITLE
The Loot Herald Project 

### ISSUE THREAD

**Issue by OExcess** [BibliothecaDAO/Frontinus-House-Docs#21]
### Proposal Title: The Loot Herald

**Name or social handle of proposer:** Loot Writers Group w/ coordination from O_Excess & Thomas Radio
**Ethereum Mainnet Address:** 0x40602EEcDB43d36f7188bAd01a5635F2515Ef765

### Project Detail
**1. Name of the Project:** The Loot Herald

**2. Project Overview:**

We are proposing the creation of the Loot Herald, a role that will act as a journalist, scribe, and evangelist of the projects within the Loot ecosystem and of the ideological nature of open-sourced public goods, decentralization, and permissionless onchain protocols. This role will pay special attention to what is being built by BibliothecaDAO/Realms, not only because the DAO is one of the most democratic, transparent and active Lootverse-inspired operations, but also because the DAO best represents the original ethos of Loot. Similar initiatives can be found in related sectors where brand, developer, and technology advocates work to promote the underlying industry.

The Herald will report and publish content related happenings within Realms and Loot through various outlets including Loot’s main social media account with ~70k followers. Further, the Loot Herald will be expanding Loot-related inspirations outside the common outlets of Twitter (X) and Discord (e.g., Instagram, Reddit, Farcaster/Warpcaster, Mirror, Substack, Instagram, Facebook, etc.).

**3. Unique or Different Aspects:**

The primary purpose in this role is to provide real-time, in-depth coverage and analysis of the Loot ecosystem with special focus on work being done within BibliothecaDAO/Realms. It will act as a bridge between creators, players, investors, and other interested parties, fostering easier onboarding for those new to the ecosystem, collaboration between project teams, and general understanding in the public sphere. To date, Lootverse projects have operated primarily in silos with little collaboration between teams; the establishment of this role will be an important step toward promoting the broader ecosystem.

**4. Target Audience:**

The targeted audience includes Loot and BibliothecaDAO/Realms holders, game developers, artists, and the broader crypto community interested in decentralized art and collaborative storytelling.

**5. Excitement to Build:**

The fusion of a journalistic/advocate role with the emerging importance of onchain, permissionless works presents an exciting and important opportunity to propel the entire NFT space forward. 

**6. Further Details:**

The journalist/herald will be responsible for curating content, conducting interviews, and providing insights into the Loot ecosystem. Collaboration with other creators, developers, and the BibliothecaDAO/Realms project will be essential. The position will not only document the ongoing evolution of Loot but also actively participate in shaping its future.

The journalist/herald will actively publish content on social media, blogging sites, and other outlets to promote BibliothecaDAO/Realms and other Loot projects

### Team:
This initiative comes from the Loot Discord Writers’ Room - a group of Loot collectors, fans and contributors interested in lore and collaborative storytelling within the Lootverse. Most of the Loot Writers are also BibliothecaDAO members. The Loot Writers will help guide the Herald at the onset but then transfer responsibility as they become comfortable w/t leading the initiative.

Contributors O_Excess and Thomas Radio are taking the lead but other contributors to the proposal include Caygeon, devondolan, Korivak, raulonastool, Ticklish, timshel, and tylerharries

### Deliverable Examples

- Publishing summarized notes from the Lord’s Table or Loot Town Square meetings.

- Newsletter overviewing happenings, accomplishments, or announcements within Loot-related projects (e.g., weekly updates on Loot Survivor high scores). 

- Producing short-form content through social media accounts and/or social media. Some examples may be short stories featuring specific Realm assets, illustrated comic panels, or art produced by Loot creatives. 

- Hosting Twitter Spaces or other social events to discuss and advertise Lootverse projects.

### Timeline and Objectives

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-d22927d5-7fff-8735-8cd1-d7845b9b2178"><h3 dir="ltr" style="line-height:1.2;margin-left: -15pt;background-color:#ffffff;margin-top:0pt;margin-bottom:12pt;padding:6pt 0pt 0pt 0pt;"></h3><div dir="ltr" style="margin-left:-15pt;" align="left">

Expected Deadline | Tasks
-- | --
September 2023 | Search and Recruitment for Suitable Candidate
September 2023 | Make a Short List of Desired Account Names: Gmail, domain name, Twitter, Threads, Reddit, Substack, etc. Create email and other communication accounts.
Sept. - Oct, 2023 | Onboarding and Orientation: Integrate the selected candidate into the Loot community, providing necessary training and orientation. BibliothecaDAO members O_Excess and Thomas Radio will act as Mentors.
Sept. - Oct. 2023 | Create visual branding, favicon, profile picture, profile banner, wordmark, etc.. Choose font and color schemes for Herald Lootverse Branding..
October 2023 | Publication of First Newsletter/Loot Issue #1, initially created by mentors and Loot Discord Writers’ Room collaboratively, and then transitioning to Herald after onboarding. The first issue should have the recent news of the Lootverse, an article about the history of Loot, and an original short story.
November 2023 | Organize and conduct the first community event. A Twitter Space, live video interview, AMA, or some other similar event, planned and operated by Herald.
Nov. 2023 - Aug. 2024 | Content Creation and Community Engagement/Collaborative Efforts - In addition to continuing to produce Loot/Bibliotheca-related content, Herald will continue community engagement efforts (e.g., virtual events, town-square discussions, hosting founder forums, etc.)
Feb. 2024 - Aug. 2024 | Impact Assessment and Sustainability Planning - In addition to tasks mentioned above, the Herald will assess its accomplishments and begin planning ways to make the role sustainable, through funding or other revenue producing tasks.

</div></b>
</body>
</html>

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-2b9111e7-7fff-39a6-a0e5-e6293fced369"><div dir="ltr" style="margin-left:-13.5pt;" align="left">

Long-term Objectives
--
Goal | Description

- Raise Awareness and  Understanding of Loot Ecosystem | Develop and execute a content and engagement strategy that educates, informs, and excites both existing members of the Loot community and potential newcomers.

- Enhance Accessibility and Inclusivity within the Loot Universe | Implement initiatives that make the Loot universe more accessible to a diverse audience, including creating guides, tutorials, and collaborating with developers to improve user experience.

- Foster Collaboration and Community Building | Act as a bridge between creators, players, investors, and other stakeholders, fostering collaboration, hosting events, and creating opportunities for community members to connect and contribute.

</div></b>
</body>
</html>

**Grant Request**
We are requesting 100,000 $LORDS per the grant requirements.

**Comment by ponderingdemocritus** [comment]
Great idea! I would like to see weekly updates on the RAW ;)

**Comment by OExcess** [comment]
Thanks - glad you see value in it! Weekly updates, spotlights on builders and players, high scores, lore overlap from other Lootverse projects, a report/newsletter/postings related to this genesis funding round -- the list goes on and on. There is a lot that folks outside Discord should hear about.

**Comment by palomato** [comment]
There’s one aspect of RAW reporting that I think is lacking- dev updates. There are two channels in BibDAO’s Discord that stream updates to the repos as they happen: #github-uodates and #github-duscussions
