### ISSUE TITLE
The Shifting Tower

### ISSUE THREAD

**Issue by lukeglwang** [BibliothecaDAO/Frontinus-House-Docs#25]
**Introduction**
Name or social handle of proposer: Lukeglw
Ethereum Mainnet Address: 0xA126F99e0DEFc3bFa963064314c4b1D54c872DCc
Twitter handle (optional): @Lukeglw

**Project Detail**
New Realms Game, original game flow is by @Fomentador, this is a proposal as an indication of interest to build this out.
[Figma Link, also work by Fomentador](https://www.figma.com/file/BnFP9JC9g6YYJk17P5oLU9/The-Ceaseless-Struggle?type=whiteboard&node-id=0-1&t=jMuB6NdTKxxq0pIA-0 )

**Character**
This is planned to be an effort of a novel community-driven AW & FOCG game studio between a few members of the Web3MQ team and several former "The Steam Awards" winning devs.

**Timeline**
Slated to be able to start around 9/1 and first prototype delivered around beginning of October.
(If Bibliotheca DAO votes to move forward, since none of us contributed to the original gameplay design)

**Grant Request**
100,000 $LORDS

**Comment by Fomentador** [comment]
Hey Luke, great to see you're giving the Shifting Tower some love. Could you give out some detail on the team and how you're structuring the phases of development of the game?
