### ISSUE TITLE
Frontinus House Builder Proposal: Fully Composable, Incentive, and Decentralized Lootverse Gaming Collaboration and Creation Network

### ISSUE THREAD

**Issue by mryings** [BibliothecaDAO/Frontinus-House-Docs#27]
# Frontinus House Builder Proposal: Fully Composable, Incentive, and Decentralized Lootverse Gaming Collaboration and Creation Network

### Introduction
Name of proposer: **Myron Will**

Contact Email: **myronzhang520@gmail.com**

Ethereum Mainnet Address: **0x19c973572339622d5ebb820111db1be3419cc603**

Any relevant links/Websites (optional): https://drive.google.com/file/d/17ubZmMCfxNeDPqxJBZiaej3_Jou57T8P/view?usp=sharing

Introduction video link (optional): https://drive.google.com/drive/folders/1y03phrP2YV8etgtw3VxSx86W7bdD1euk?usp=sharing

### Project Detail

-  **What is the name of the project:** Fully Composable, Incentive, and Decentralized Lootverse Collaboration and Creation Network

-  **What is it based upon:** It will be based on Lootverse to enrich the Lootverse ecosystem and empower the development of games in Lootverse

-  **What does this do that is unique or different to other projects:**

  Based on the original Loot NFT with a few gaming words, many derivative projects like new NFTs and games come out to expand those words and form collective narration. They form a prosperous ecosystem called Lootverse, which is crucial to the value of Loot. Therefore, we should support the following projects in Lootverse in any ways as much as possible to promote their development, and their success can also make Loot more valuable. However, under the current mode of Lootverse, the original project and its following new project are essentially seperate except sharing the same gaming words without further mutual benefits.

  To address this issue, we aim at enabling the open, decentralized, and permisionless upgradability and composability of projects within Lootverse. Each original project can allow any other people to freely upgrade it with new projects, so everyone can freely make new projects to revise and improve the orginal project. Based on the original project, the new project can share the resources with the original project like user network and token model with no need to build from scratch, and get the support from the original project like technical foundation, stakeholder community, and creator economy to grow faster and better. In return, the new project can also make the original project become better, so the original project can attract more users and earn more revenue. As a result, the orginal project and its new projects made by others can help each other for mutual promotion in Lootverse.

- **Who is the target audience of this project**: The followers of the original project like the collectors of the NFT and the players of the game. They want to make the original project better with innovative upgrades, because it will benefit the original project to benefit themselves. However, the founder of the orignal project may not realize the value of their improvements, so they want to fork the original project with new branches to upgrade and improve by themselves.

- **What about this project excites you to build**: We can make Lootverse projects can not just share gaming words and collective stories, but more importantly exchange the more valuable and essential development resources to assist each other for mutual benefit, which makes Lootverse a more capable and thriving community of shared interests.

-  **Any further details you might want to elaborate on:** Take a Lootverse on-chain gaming project for example. The founding team of the original project doesn't need to make a whole game. They can just make a part first like game equipments. Then others can freely add any other parts to the original project like characters and storylines, or just revise the original project such as adding other equipments to upgrade the original project to the new project. Likewise others can also continue upgrading the new project until forming an integrated game. Each project can issue its token, and when buying the whole game, the tokens of all composed projects will also be purchased together, so the earnings of the game will be distributed among all related projects according to their contributions. 

### Character
We are a team from CMU, UC San Diego, and UC Berkeley with different expertise covering design, research, development and business. We have strong interests, capacity and skillsets on the innovative entrepreneurship of blockchain, crypto and web3. We love Lootverse and fully devote ourselves into contributing to it as much as possible. We are all very thrilled about this project and have fully prepared for starting our adventure journey via your grant.

- **Myron Will** graduated from Carnegie Mellon University and obtained master degree in Technology Innovation Management. He keeps doing technical research and product design on blockchain, crypto and Web3 endoresed and funded by Ethereum Foundation. He also made several entrepreneurship projects to promote the decentralized composability and upgradability of blockchain.

- **Miguel Monares** graduated from The University of California, San Diego, double majoring in (1) Math-CS and (2) Cognitive Science with a specialization in machine learning. He was previously a researcher at the National University of Singapore where he built infrastructure for cross-chain deFi regulation and developed a tool to benchmark blockchains and dApps. Miguel has advised the development of web3 ventures for start-ups and corporations, and he won the Franklin Templeton Blockchain Fintech competition with his project, SugarBlock, a P2P marketplace and donation platform for nonprofit organizations. He is passionate about building the next generation of web3 tools toward a decentralized future.

- **Navein Suresh** majors in computer science and applied mathematics at the UC Berkeley. He had strong blockchain programming skills and mastered various blockchain-related technologies well. He fully devotes himself into the coding and development of this project.

### Timeline
We will start once receving the grant and we estimate we need about 6 months to build and run the proposed project successfully.

### Objectives
| Objective     | Contributor   | Estimated deadline  |
| ------------- |:-------------:| -------------------:|
| Improve the project proposal the determine the final version | Myron, Miguel,Navein | 2023/11/01 |
| Design the product according to the proposal | Myron, Miguel,Navein | 2023/12/01 |
| Develop our product | Myron, Miguel,Navein | 2024/01/01 |
| Conduct technical testing and user evaluation | Myron, Miguel,Navein | 2024/02/01 |
| Release the final version and promote it in the community | Myron, Miguel,Navein | 2024/03/01 |
| Successfully run the first round of Lootverse projects in our network | Myron, Miguel,Navein | 2024/04/01 |

### Grant Request
Hugely appreciated if we could get the standard 100,000 Lord to improve our proposal and develop our project with sufficient funding. Feel free to reach out to us to put forward any golden feedback and critiques, and we will revise our proposal accordingly. Welcome to join us and we can work on this project together to promote the development of Lootverse. Thanks a lot!

**Comment by palomato** [comment]
Help me understand-

This is a project to tokenize various components of a game? Like someone makes a simple game with Loot NFTs, your platform issues a token. Someone else adds a module to the game, your platform issues a token. Then if someone wants to 'own' the game they buy both tokens?

And the product you're developing is a set of contracts to do this tokenization, and a web UI frontend?

I've seen blockchain games that require an NFT to play, or that you pay to play. But not sure I've heard of a blockchain game that you 'buy' as you would a console game. Is there an example? Thanks.

**Comment by mryings** [comment]
Dear @palomato:
Hello!

Thanks for your timely review and comments! Responding to your inquiries, this proposed project is composed of two parts for fully decentralized and incentive gaming collaboration and creation in Lootverse. 

One part is enabling **permissionless upgradability** for any projects in Lootverse. If you make a project in Lootverse, you can open the right to improve your project to everyone in the community. Everyone can freely make any new projects based on your project to revise existing parts or add new parts to your project to make it better. For example, suppose Azuki is a project in Lootverse. If the founding team of the original Azuki upgrades Azuki to a new version, which is so inferior that didn't satisfy the community, the value of Azuki would suffer a lot. However, in our project, we enable the community to fork and upgrade the original Azuki to different new versions with better new works as new branches to meet the expectations of the community. In this way, the development of Lootverse projects could be fully decentralized without being controlled by the founder of the project, so the project can be more qualified and valuable without being limited by the capacity and reliability of the founder. 

![image](https://github.com/BibliothecaDAO/Frontinus-House-Docs/assets/110052573/bed326b6-c3da-47d2-b912-dfb34e0c229b)

Under the mode of fully decentralized upgradability above, each project could be composed of different versions and works made by different entities, so how to fairly and equally distribute the earnings of the project among different composed works is a key issue. Our solution is for each work to launch their own token, and when buying the whole project, the tokens of all its composed works will also be purchased. For example, following the graph above, Version 1 has Token 1 for Part 1, Version 2 has Token 1 and Token 2 for Part 1 and Part 2, Version 3 has Token 2 and Token 3 for Part 2 and Part 3. Suppose the price of Token 1 is $2, and Token 2 is $3, then the price of Version 2 is $2+$3=$5. Suppose the price of Token 3 is $5, then when Version 3 earns $8, it should distribute to Version 2 $3 for its Part 2, so Version 3 can finally have $5 for its Part3.

![image](https://github.com/BibliothecaDAO/Frontinus-House-Docs/assets/110052573/bb2f15d7-c853-4bad-9c1f-7a4ffa7fa693)

In order to do so, our project will have smart contracts to enable permissionless upgradability based on the existing smart contract upgrade proxy pattern. It can also have front-end and back-end to enable creators to easily upload their new works to freely upgrade any existing works. All different works will coexist for players to freely choose and buy. Good works will be identified and stood out, and bad works will be obsoleted naturally.

Not sure what you mean by "as you would a console game". Everyone can buy the token of a project to use the project or trade the token, but there is no need to buy the token of the project to upgrade the project as the upgradeability is open, unlimited and permissionless. 

Any other questions feel free to ask and we will answer in time. Thanks a lot!

**Comment by r0man1337** [comment]
I don't understand exactly what you want to do, the idea sounds quite abstract. I'm also not sure that the problem you are talking about really exists in our case. Isn't Lootverse already decentralized? Both BibliothecaDAO and RoyaltyDAO are managed by community, there are no centralized entities who rules the projects. Code and media resources are usually under CC0 license. So anyone can make derivative projects and monetize them however they want, we can't put any restrictions on it. I mean, if I understood correctly, what you described is quite available now, I don't understand what kind of product you want to make and what its functionality is.

IMO Lootverse is already permissionless and composable ecosystem.

**Comment by mryings** [comment]
Dear @palomato:

Hope our answer to your questions works! Feel free to ask any other questions or put forward any critiques if you have. Otherwise hugely appreciated if you could support our proposal and vote for it! Thanks a lot!

**Comment by mryings** [comment]
Dear @r0man1337:
Hello!

Thanks for your review and critiques! Sorry it's a very innovative but valuable ecosystem development mode more decentralized, unlimited, and productive than the existing one, so it needs more explanation and takes some time to understand. But it's worthwhile and thanks for your patience!

Yes anyone can freely copy and modify the existing Lootverse projects to make new ones, but it's something like **hard fork** because new and original projects are essentially **separate**. The original project can open and share its content and code with new projects under CC0 license, but not its **internal resources** like states, community, token model, which are actually more essential and valuable. In this way, the original project still has clear boundaries and isolation to prevent any other new projects from being built based on it. To form a fully interconnected and reciprocal ecosystem, instead, the original project should fully open and share its internal resources with any different new projects based on it to help them grow better. New projects will also improve and develop the original project to make it become better beyond its own upper limit, so new and original projects can help and benefit each other. 

In order to do so, technically the original project should allow any other new projects made by anyone become its **new versions** like **soft fork** rather than hard fork with full composability, interoperability and compatibility. New project is just like **new branches** of the original project, not two separate and isolated projects. For example, when players from the original project play any derivative new projects made by others, they can have the same token and states as they already have in the original project with no need to play from scratch. 

Economically, as the original project helps its following new projects with its internal resources, if new projects succeed, it should also distribute their earnings with the original project in return. Please note that such a mode is fully **permissionless**. All new projects can directly be built based on the original project and share its internal resources no matter what they are and who make them with no need to get the permission from the original project first. It means that even if the original project doesn't like any new projects made by anyone, they can't prevent them. All different projects will coexist in the market for end users to identify and choose, so it's up to players not the original project. If a project is not good, it should be denied by end users naturally, but not the original project.

We think the current Lootverse doesn't have such a fully decentralized, permissionless and unlimited mode of gaming ecosystem development. In analogy with American history, It will make projects in Lootverse not like loose confederation of states, but tightly related and united commonwealth, which will be more powerful and beneficial. Any questions feel free to ask us, and hope can get your golden critiques and generous support! Thanks a lot!

**Comment by mathida520** [comment]
Dear @r0man1337 :

Hope our answer to your questions works! Feel free to ask any other questions or put forward any critiques if you have. Otherwise hugely appreciated if you could support our proposal and vote for it! Thanks a lot!
