### ISSUE TITLE
AW Research - Hacker House

### ISSUE THREAD

**Issue by CheDAO-Labs** [BibliothecaDAO/Frontinus-House-Docs#3]
# Frontinus House Builder Proposal

### Introduction
Name or social handle of proposer: kaikai

Ethereum Mainnet Address: 0x8046108b92EEAa28b8970B6294BfD432dc382c7D

Twitter handle (optional): @AW_Research

Any relevant links/Websites (optional): https://mirror.xyz/0x8046108b92EEAa28b8970B6294BfD432dc382c7D, https://chedao.notion.site/AW-Research-Collection-234dcfb1fc4441f9b0c14725b01fb921?pvs=4

### Project Detail
AW Research is dedicated to advancing on-chain gaming through our educational resources, industry insights, and community events.

We are thrilled to announce the upcoming Relams Hacker House - a 4-7 day immersive gathering this October focused on expanding the possibilities of the Relams Autonomous World.

In this mansion provided by AW Research, participants will collaborate intensively to build, experiment, and create new modules and assets for Relams using its powerful SDK and APIs. With full support from the Relams development team, you'll bring your ambitious gaming visions to life.

Expect little sleep, boundless creativity, and nonstop teamwork. Attend masterclasses, demo your projects, and compete for grants. This is your chance to push Realms to new heights.

By facilitating this hacker house, AW Research aims to drive innovation, education, and engagement in on-chain gaming. Let's build the future of Relams together. Welcome to the Relams Hacker House!

### Character
I am Kaikai, and I am at the helm of all operations at AW RESEARCH. My passion for blockchain technology and on-chain gaming has driven me to create a platform that not only informs but also empowers enthusiasts. From curating insightful tutorials and tracking industry trends to fostering a sense of community through engaging events, I am dedicated to advancing the world of on-chain gaming. Join me on this exciting journey as we navigate the cutting edge of technology and innovation together.

### Timeline
We plan to host a hacker house for Realms on Oct.

### Objectives

| Objective     | Contributor   | Estimated deadline  |
| :-------------: |:-------------:| :-----------------:|
| Realms Hacker Houses   | kaikai     | 31/10/23            |

### Grant Request
We expect a total cost of 80000 $LORDS.

**Comment by palomato** [comment]
- Where will the hacker house be located?
- How many participants will be able to attend?

Thanks for making this proposal 👍

**Comment by Calcutatator** [comment]
gm, sounds great ser and I love the fact its something a bit different 🔥 

For clarity this round is 5 grants of 100,000 LORDS and not USDC. Assuming LORDS is acceptable could you amend your amount to lords. This is as standard 100,000 LORDS but can be less if that is of excess.

**Comment by CheDaoxyz** [comment]
> * Where will the hacker house be located?
> * How many participants will be able to attend?
> 
> Thanks for making this proposal 👍

Accommodation and meals are provided for up to 20 participants during the Hacker House event. If the number of participants exceeds 20, accommodation and meals will not be provided, and individuals will need to arrange their own accommodations and dining.

LOCATION: Shanghai, CN

**Comment by CheDAO-Labs** [comment]
> gm, sounds great ser and I love the fact its something a bit different 🔥
> 
> For clarity this round is 5 grants of 100,000 LORDS and not USDC. Assuming LORDS is acceptable could you amend your amount to lords. This is as standard 100,000 LORDS but can be less if that is of excess.

Of course, we can totally accept lords.

**Comment by CheDAO-Labs** [comment]
> gm, sounds great ser and I love the fact its something a bit different 🔥
> 
> For clarity this round is 5 grants of 100,000 LORDS and not USDC. Assuming LORDS is acceptable could you amend your amount to lords. This is as standard 100,000 LORDS but can be less if that is of excess.

just updated grant request for $lords

**Comment by CheDAO-Labs** [comment]
> > * Where will the hacker house be located?
> > * How many participants will be able to attend?
> > 
> > Thanks for making this proposal 👍
> 
> Accommodation and meals are provided for up to 20 participants during the Hacker House event. If the number of participants exceeds 20, accommodation and meals will not be provided, and individuals will need to arrange their own accommodations and dining.
> 
> LOCATION: Shanghai, CN

update:

Hosting a hacker house in Shanghai is just a beginning. In the future, the CHEDAO team can also venture to various parts of the world and organize hacker houses in the most suitable locations.
