### ISSUE TITLE
Devil Cell

### ISSUE THREAD

**Issue by CheDAO-Labs** [BibliothecaDAO/Frontinus-House-Docs#4]
# Frontinus House Builder Proposal
### Introduction
Name or social handle of proposer: David

Ethereum Mainnet Address: 0x429a87e7c924C45fC5C5dF80c63Ffec7919A6720

Twitter handle (optional): @CheDAOLabs

### Project Detail
DevilCell is an ecological simulation on-chain game where players can choose creatures with different attributes to interact within the ecosystem. Interactions lead to creature evolution, and players select diverse evolutionary paths based on interactions with other creatures. The game encompasses attribute design, a combat system, breeding mechanisms, and uses an experience-based ranking system to encourage player engagement. The game leverages blockchain technology to facilitate in-game economics and interactions.

### Character
Hey, I'm David, the driving force behind Devilcell. As the Project Manager, I'm fueled by a passion for innovative gaming. Devilcell isn't just a game; it's a vision of interactive entertainment that marries creature interactions, $lord tokens, and LOOT integration. I'm thrilled to lead the charge in creating a dynamic blockchain-based ecosystem that brings unique attributes, strategic combat, and immersive experiences to players. Let's embark on this exciting journey together and redefine the future of gaming.

### Timeline
This will be a 3 month build collaborating with the greatest of Devilcell builders in the world. I estimate a start date of 25/08/2023 and end date of 30/11/2023

### Objectives

| Objective     | Contributor   | Estimated deadline  |
| :-------------: |:-------------:| :------------------:|
| successfully implements a smooth game progression      | David     | 30/09/23            |
| Integrate the $Lords into devilcell's economic system  | David     | 31/10/23            |
| Integrate the Loot items into devilcell                | David     | 30/11/23            |

### Grant Request
We expect a total cost of 100000 $LORDS.

**Comment by ponderingdemocritus** [comment]
This all sounds great. It sounds like a very large scope.

I would like to know more about the game and how you plan on building it including:

- Technology used
- Smart contract Architecture thinking
- First features to implement
- Playtesting strategy
- Any mockups you might have

**Comment by palomato** [comment]
Sounds interesting! Will Devil Cell be similar to any game that we'd know--like Axie Infinity?

>  Devil Cell...marries creature interactions, $lord tokens, and LOOT integration
Could you talk more about the Lords and Loot integration? How are loot/lords used?

Thanks for making this proposal 👍

**Comment by Calcutatator** [comment]
gm! Sounds really cool and I would love to hear more as per the other comments.

For clarity the round is 5 grants of 100,000 Lords and not USDC. I hope that's ok ser! Give me a message if you have any confusions happy to help :D

**Comment by CheDAO-Labs** [comment]
> This all sounds great. It sounds like a very large scope.
> 
> I would like to know more about the game and how you plan on building it including:
> 
> * Technology used
> * Smart contract Architecture thinking
> * First features to implement
> * Playtesting strategy
> * Any mockups you might have

**Technology used**

- Smart contracts will deployed on StarkNet, with the contract logic implemented using the Cairo. 
- The game engine utilized is Dojo. 
- The client-side is developed using JavaScript and TypeScript, 
- The rendering engine is based on LayaAir3.

**Smart contract Architecture thinking**
- The smart contract architecture is based on Dojo's built-in ECS model.

**First features to implement**
- Initialization of the game world.
- Player registration and login module.
- Interactive module for in-game player actions.
- Marketplace.

**Playtesting strategy**
- Feature testing.
- Gameplay flow testing.
- Unauthorized action testing.
- Conducting various testing tasks corresponding to different scenarios.

**Any mockups you might have**
Yes, it's still in progress!
![image](https://github.com/Calcutatator/Frontinus-House-Docs/assets/135700837/59a62375-0bcb-4d70-83ae-9e9293849457)

**Comment by CheDAO-Labs** [comment]
> # Frontinus House Builder Proposal
> ## _**Devil Cell**_
> ### Introduction
> Name or social handle of proposer: David
> 
> Ethereum Mainnet Address: 0x429a87e7c924C45fC5C5dF80c63Ffec7919A6720
> 
> Twitter handle (optional): @CheDAOLabs
> 
> ### Project Detail
> DevilCell is an ecological simulation on-chain game where players can choose creatures with different attributes to interact within the ecosystem. Interactions lead to creature evolution, and players select diverse evolutionary paths based on interactions with other creatures. The game encompasses attribute design, a combat system, breeding mechanisms, and uses an experience-based ranking system to encourage player engagement. The game leverages blockchain technology to facilitate in-game economics and interactions.
> 
> ### Character
> Hey, I'm David, the driving force behind Devilcell. As the Project Manager, I'm fueled by a passion for innovative gaming. Devilcell isn't just a game; it's a vision of interactive entertainment that marries creature interactions, $lord tokens, and LOOT integration. I'm thrilled to lead the charge in creating a dynamic blockchain-based ecosystem that brings unique attributes, strategic combat, and immersive experiences to players. Let's embark on this exciting journey together and redefine the future of gaming.
> 
> ### Timeline
> This will be a 3 month build collaborating with the greatest of Devilcell builders in the world. I estimate a start date of 25/08/2023 and end date of 30/11/2023
> 
> ### Objectives
> Objective	Contributor	Estimated deadline
> successfully implements a smooth game progression	David	30/09/23
> Integrate the $Lords into devilcell's economic system	David	31/10/23
> Integrate the Loot items into devilcell	David	30/11/23
> ### Grant Request
> We expect a total cost of 150000 $LORDS.

**Just updated the Grant Request for $LORDS**

**Comment by CheDAO-Labs** [comment]
> 

just updated the grant request sir

**Comment by CheDAO-Labs** [comment]
> gm! Sounds really cool and I would love to hear more as per the other comments.
> 
> For clarity the round is 5 grants of 100,000 Lords and not USDC. I hope that's ok ser! Give me a message if you have any confusions happy to help :D

just updated the grant request sit

**Comment by Fomentador** [comment]
The concept is very novel and interesting, great to see it. Merging all these game systems - which are very complex on their on - into an on-chain game seems quite the challenge, I would love to see game design documentation to better understand how you're intending to accomplish that. 

You shared a doc here but it's too small to read and it's all in Chinese, I think.

**Comment by CheDAO-Labs** [comment]
> 
Currently, we only have an internal document, but it's not suitable for external use. This document is not comprehensive and is not in English. However, to help users understand better, I can provide a brief explanation of the roles of C&C, LOOT, and $LORDS in DevilCell:


### C&C usage in game
Users begin by crafting their own cells at the start of the game. These cells maneuver across the dungeon map, which is represented by CC NFTs, acquiring resources, competing, reproducing, and engaging with a variety of events.
### Loot items usage in game
Similar to how characters can equip loot items in other games, in Devilcell, each cell can also be equipped with loot items. Different loot items have various positive effects on cells. For instance, some items might increase a cell's health, leading to a longer lifespan, enhance a cell's agility to improve its ability to escape, or boost a cell's attack capabilities, influencing the outcomes of battles with other cells.
### $LORDS usage in game
In Devilcell, there exists a marketplace for cells, where players can engage in breeding with cells owned by other players through listing their own cells for sale (acting as buyers). Players who list their cells can set specific attribute conditions for the cells owned by other players (acting as sellers). If the conditions are met, the player owning the listed cell (seller) can use their cell for breeding. The resulting offspring cell belongs to the player who listed it (buyer), and the gas cost of the breeding operation is covered by the player providing the cell. The token corresponding to the listing price goes to the participant (seller). $LORD will serve as the circulating currency in this marketplace.
