### ISSUE TITLE
Comprehensive suite of on-chain data dashboards

### ISSUE THREAD

**Issue by gnart33** [BibliothecaDAO/Frontinus-House-Docs#6]
# Frontinus House Builder Proposal

### Introduction
Name or social handle of proposer: **Trang**

Ethereum Mainnet Address: **0x37B275764442a9bBC1cB572aF05C4De2bFfFcf60**

ENS name (optional): **phowr.eth**

Twitter handle (optional): **trangnv_**

### Project Detail
Providing the comprehensive suite of on-chain data dashboards

1. L1 dashboards build on Dune

- These are straightforward to build as data are available on Dune. If necessary, custom data sources, dashboards will be done with [checkthechain](https://github.com/checkthechain/checkthechain) and Jupyter notebooks
- L1 $LORDS [token](https://etherscan.io/token/0x686f2404e77ab0d9070a46cdfb0b7fecdd2318b0) 
- L1 bridge [contract](https://etherscan.io/address/0x023A2aAc5d0fa69E3243994672822BA43E34E5C9)
- [LootRealm](https://etherscan.io/token/0x7afe30cb3e53dba6801aa0ea647a0ecea7cbe18d) staking/buying activities

2. Starknet dashboards

- Events data will be indexed using [Checkpoint](https://checkpoint.fyi/), dashboards built with Jupyter notebook, similar to [this](https://trangnv.github.io/starknet-watcher/notebooks/accounts_dashboard.html) 
- Starknet $LORDS [token](https://starkscan.co/token/0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49) 
- Starknet bridge [contract](https://starkscan.co/contract/0x07c76a71952ce3acd1f953fd2a3fda8564408b821ff367041c89f44526076633)
- Eternum and Loot survivors on-chain game data, any event emitted by the contracts can be indexed using Checkpoint

3. [Forta](https://explorer.forta.network/) bot to notify on-chain activities of $LORDS, LootRealm on Ethereum

### Character
I am Trang, I’ve contributed to a couple of Starknet projects, including data engineering/analytic, Cairo1. Before that I had a few on-chain data engineering and analysis projects elsewhere.
This would be the first time I make contribution to the BibliothecaDAO ecosystem, very excited to start the journey with the DAO.

### Timeline
3 months building and collaborating with DAO members, starting 26 August

### Objectives
| Objective     | Contributor   | Estimated deadline  |
| ------------- |:-------------:| -------------------:|
| 1st version dashboards   | Trang | 25/09/23           |
| Feedback   | Trang | 25/10/23            |
| Notification bot   | Trang | 25/11/23            |

### Grant Request
80000 $LORDS

**Comment by palomato** [comment]
> Eternum and Loot survivors on-chain game data, any event emitted by the contracts can be indexed using Checkpoint

Depending on what is displayed, this could be a useful source of intel for players. For example the ability to filter realms by resource (highest raidable quantity in Vault), weakest armies, p2p available trades, etc.

Also here is a dune dashboard for the Realms NFTs that might be useful for you: https://dune.com/redbeard/Realms-(for-Adventurers)-NFT

**Comment by Calcutatator** [comment]
Great proposal ser. Looks like an awesome way to get a lot of good combined info in one place 👑

**Comment by trangnv** [comment]
Thank for the feedbacks, looking forward to it.
