### ISSUE TITLE
Last Standing - The Ultimate Survival Game

### ISSUE THREAD

**Issue by GrugLikesRocks** [BibliothecaDAO/Frontinus-House-Docs#8]
### Introduction
Name or social handle of proposer: **Grug**

Ethereum Mainnet Address: **0xAe61D06C4838f0f3AD10AdB5db7eF1D04E5E26e2**

ENS name (optional): **gruglikesrocks.eth**

Twitter handle (optional): **@GrugLikesRocks**

### Project Detail

# 1. Overview

---

## ⇒ Key Points

**Title**

▶️ Last Standing (subject to change)

**Genre**

▶️ Tactical Fully On-Chain Game

**Number of players**

▶️ Up to the number amount of explorers existing (exact amount TBD), PVE

**Target audience**

▶️ Mainly focusing FOCG and Starknet users, suitable for casual gamers. No specific age range or gender

**Platforms**

▶️ PC, Mobile

**Game engine/ Tech Stack**

▶️ Dojo, Cairo, Phaser, React. (Subject to change) 

**Game Identity**

▶️ Explorers will head into the wild to build outposts around the game map. Randomly generated events will damage outposts owned by the players, where the last standing one will win a final jackpot.

**Graphic style**

▶️ 2D, Hex Tiles Map

## ⇒ The 3Cs

**Camera**

▶️ Scrolling 2D camera from above the Map

**Character** 

▶️ The Players will be able to control and mint their explorers and create/defend/trade outposts.

**Controller** 

▶️ Point and Click mainly, but users will be able to move around the map with arrow keys and WASD

# 2. The Game

---

**Pitch & Story**

▶️ Players will have to mint their explorers which will go into the wild building outposts. These outposts will have to be defended from random events that will affect random targets. The proud owner of the last standing outpost reaps a rich pool of $LORDS, sourced from defences setup fees and game initiation. The value of this pool corresponds directly to the total LORDS gathered during gameplay, with a fraction allocated for game developers and Bibliotheca DAO.

The story itself will evolve in the next seasons of the game but game mechanics will stay the same.

**Design Pillars**

▶️ Randomness. 

Low Effort. 

Strategic. 

Based on the Realmverse/Lootverse

Fully On-Chain Game

**Game progression**

▶️ The first release of the game will have 2 main phases:

**Preparation phase** - Players will be able to mint explorers and buy defences for their outposts.

Each defence will grant the outpost 1 extra life.

The amount of defences available will be limited and they can only be purchased during the preparation phase with a Variable Rate Gradual Dutch Auction (will spice things up!)

The preparation phase will last a week or will end as soon as all the explorers have been minted.

**Main game phase** - Once the preparation phase is over, explorers will be sent into the wild trying with the scope of building outposts. Dangerous events will randomly happen which will damage random outposts across the map. When an outpost reach 0 lives is destroyed and is out of the game.

During the main game phase, players can trade outposts and reinforcements between themselves on a secondary market.

The season will end when there is only one outpost standing, which will win the jackpot made of a rich pool of $LORDS, sourced from buying defences and minting explorers.

In future seasons players will be able to:

- Customize the shape and attributes of the maps, to be part of this voting phase you have to own a Realm. 1 Realm = 1 Vote
- Trade non-dead explorers whilst the main game is running
- Explorers that belong to a certain orders can vote to farm a resource which will give a boost to a certain type of defence
- The amount of explorers will change every season based on the amount minted in the previous round.

**Winning and losing conditions** 

▶️ A players loses when an outpost that he/she owns goes to 0 lives.

A player win the game if he/she is the owner of the last outpost standing.

**Look & Feel**

▶️ The game should have a similar look of [[Catan](https://www.catan.com/catan)](https://www.catan.com/catan) board game but much bigger size. The map should be much bigger as each explorers minted will build an outpost on one hex tile on the board. 
The game will be in 2D. Design might change.

Some references:
![map1](https://github.com/Calcutatator/Frontinus-House-Docs/assets/92889945/3b66747a-eb3d-4fb5-9c46-4b0005e02e2d)

![map2](https://github.com/Calcutatator/Frontinus-House-Docs/assets/92889945/9e1d5cb1-823b-4232-9b74-dcca1bc0eb8a)

# 3. Market

---

**Unique Selling Points** 

▶️ Low cost

Players will be able to spend $LORDS to mint their explorers and buy/trade defences

Low Effort, Low Maintenance

Developed with Dojo

### Character
I'm Grug, founder of the Grug's Lair, OG member of Bibliotheca DAO and leader of the dark army. I'm green, I carry a big club with me and I'm angry most of the times. 
My background in Game dev, game mechanics and UX/UI makes it the perfect mix for tackling the task of making a game using Dojo built in the RAW. I'll be taking on the task with other 3 talented developers.

Alexhalo: Deeply passionate about crafting video games with cutting-edge technologies. My special interest lies in creating games that incorporate seamless procedural generation, backed by proficiency in C++, C#, and the Unity game engine.

Yao: With a solid decade of experience as a full-stack engineer and 2 years dedicated to crypto development, I bring a wealth of expertise to the table. I am a fervent advocate for on-chain games, holding a strong belief in their potential. Beyond that, I am deeply enthusiastic about DAOs and have actively contributed as both an enthusiast and a builder of DAO tooling.

Felix: Passionate about web3, open source, and community-driven projects. Proficient in Cairo, React, and Java with a focus on creating impactful and user-centric experiences.

### Timeline
Roughly 3/4 months to publish the first working product (including testing and feedback)

### Objectives
| Objective     | Contributor   | Estimated deadline  |
| ------------- |:-------------:| -------------------:|
| First game prototype 1st October | Grug, alexhalo3115, felix_luo, yaometaforo | 01/10/23          |
| Launch of Alpha, playtesting & feedback 1st November | Grug, alexhalo3115, felix_luo, yaometaforo | 01/11/23           |
| 1st Season Release date 1st December | Grug, alexhalo3115, felix_luo, yaometaforo | 01/12/23            |

### Grant Request
100,000 $LORDS

(added in team members' descriptions)

**Comment by palomato** [comment]
Sounds interesting-
- So we mint an adventurer, then the adventurer travels on the map to a location we choose to build an outpost? I'm wondering what the adventurer does.
- Is there a limit to how many outposts we can have?
- Is there a strategy to where you build outposts?

**Comment by GrugLikesRocks** [comment]
> 
You mint an explorer (which is not the same as the Biblio adventurer) and you send him into a location (one of the hexagon tiles in the map) to build the outpost. The adventurer then will stay in the outpost and defend the outpost. 1 Explorer = 1 Outpost.

An address can mint as many explorers as they want. Again 1 explorer = 1  Outposts

No specific strategy as the events will happen randomly. After the first season there will be more strategy implied in how to defend the outposts. But attacks on the map will be random so it's down to luck

**Comment by Fomentador** [comment]
Liked the pitch, seems a simple game that can still be fun and dynamic. But I'd like to understand the game loop better. 

If events are random and there's no PvP, what'll the player do, what's the tactical gameplay? If it's purely luck, is the loop just building outposts, buying as much defence as I can and waiting until luck decides the winner?

**Comment by Fomentador** [comment]
Ah, sorry, I wasn't specific enough. I understand that you have future implementations planned which will add more depth to gameplay. But specifically for this Season 1 there's no strategic depth, correct? Players just build outposts, buy as much of the  defences you listed as they can, and let random events determine the winner. In this sense, the proposal's objective is to build the infrastructure for different game mechanics to be implemented at later Seasons?

I really like how you structured the implementation in stages and submitted the proposal only for stage 1, btw. It demonstrates a clear understanding of scope.

**Comment by GrugLikesRocks** [comment]
Yeah that's correct. First season will only have the very core mechanics, which will be the base of the game in the future.
